### PR TITLE
Added Binary Search algorithm in javascript

### PR DESCRIPTION
**Pull request by sudo-jarvis**

### CODE REVIEW

**Review by DevAffan — COMMENTED** [review]
Good.

**Comment by DevAffan** [comment]
There is no need to add a hacktoberfest tag here, your PR has been counted on your hacktoberfest account, you may check.

**Comment by DevAffan** [comment]
if there is still any confusion or questions you may ask.

**Comment by sudo-jarvis** [comment]
Yes its showing now, Thankyou.

**Comment by DevAffan** [comment]
No problem.

**Pull request merged**
