### PR TITLE
Powerset program recursion codestudio

### PR DESCRIPTION
**Pull request by bhaveshgarg2000**
Add HacktoberfestAccepted label before merging

### CODE REVIEW

**Comment by bhaveshgarg2000** [comment]
Please add hacktoberfest label

**Comment by DevAffan** [comment]
Don worry your request will be counted on hacktoberfest there is no need to add labels, but if you say i do.

**Comment by bhaveshgarg2000** [comment]
Thanks @DevAffan

**Comment by DevAffan** [comment]
No Problem.

**Pull request merged**
